// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoCoreApp.Models;

namespace TodoCoreApp.Migrations
{
    [DbContext(typeof(TodoItemDetailContext))]
    [Migration("20211008153505_AddIsCompletedProperty")]
    partial class AddIsCompletedProperty
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TodoCoreApp.Models.TodoItemDetail", b =>
                {
                    b.Property<int>("TodoItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("TodoItemDescription")
                        .HasColumnType("nvarchar(170)");

                    b.Property<string>("TodoItemTitle")
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("TodoItemId");

                    b.ToTable("TodoItemDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
